name: merchant_order_tracker
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.2.1
  # Remove this line as `change_app_package_name` is not a regular dependency
  # dev_dependencies:  
  change_app_package_name: ^1.3.0
  http: ^1.2.2
  cloud_firestore: ^5.4.1
  syncfusion_flutter_xlsio: ^26.2.14
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  firebase_core: ^3.4.1
  google_maps_flutter: ^2.9.0
  firebase_messaging: ^15.1.1
  firebase_storage: ^12.3.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/merchant_delevery_bike.png
