// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATug27i-ufGkXuJBpc6Z4dLZUtqdwmucs',
    appId: '1:567699070935:web:115e3d4cdcc70f9176b592',
    messagingSenderId: '567699070935',
    projectId: 'coding-task-539af',
    authDomain: 'coding-task-539af.firebaseapp.com',
    storageBucket: 'coding-task-539af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7qPNSaTp_MoXw0EBBRvENFVKWw4h4slA',
    appId: '1:567699070935:android:c51c03bcbf590c6b76b592',
    messagingSenderId: '567699070935',
    projectId: 'coding-task-539af',
    storageBucket: 'coding-task-539af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArlSa20wAbUVz8HQ9yKAVsolgZaHt0VVk',
    appId: '1:567699070935:ios:2149c233472e5e8876b592',
    messagingSenderId: '567699070935',
    projectId: 'coding-task-539af',
    storageBucket: 'coding-task-539af.appspot.com',
    iosBundleId: 'com.assignment.merchantordertracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArlSa20wAbUVz8HQ9yKAVsolgZaHt0VVk',
    appId: '1:567699070935:ios:12d7e7d45c5b9f8d76b592',
    messagingSenderId: '567699070935',
    projectId: 'coding-task-539af',
    storageBucket: 'coding-task-539af.appspot.com',
    iosBundleId: 'com.example.merchantOrderTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATug27i-ufGkXuJBpc6Z4dLZUtqdwmucs',
    appId: '1:567699070935:web:873092f5b1b2643e76b592',
    messagingSenderId: '567699070935',
    projectId: 'coding-task-539af',
    authDomain: 'coding-task-539af.firebaseapp.com',
    storageBucket: 'coding-task-539af.appspot.com',
  );

}